spring:
  application:
    name: discovery
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/config/
            - file:./config/

server:
  port: 8761

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

#todo: one property for all services
service:
  order:
    url: http://localhost:8080/api/order/

# could be used for debugging
#logging:
#  level:
#    org:
#      springframework: TRACE
